<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" total="5" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="34871" started-at="2017-01-17T19:27:15Z" finished-at="2017-01-17T19:27:50Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="34871" started-at="2017-01-17T19:27:15Z" finished-at="2017-01-17T19:27:50Z">
      <class name="test.TestAppium">
        <test-method status="PASS" signature="lobby1Testcase()[pri:1, instance:test.TestAppium@10bbd20a]" name="lobby1Testcase" duration-ms="22278" started-at="2017-01-18T00:57:15Z" finished-at="2017-01-18T00:57:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lobby1Testcase -->
        <test-method status="FAIL" signature="room1TestCase()[pri:2, instance:test.TestAppium@10bbd20a]" name="room1TestCase" duration-ms="682" started-at="2017-01-18T00:57:37Z" finished-at="2017-01-18T00:57:38Z">
          <exception class="org.sikuli.script.FindFailed">
            <message>
              <![CDATA[Text search currently switched off]]>
            </message>
            <full-stacktrace>
              <![CDATA[FindFailed: Text search currently switched off
  Line 1671, in file Region.java

	at org.sikuli.script.Region.wait(Region.java:1671)
	at test.TestAppium.room1TestCase(TestAppium.java:131)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1137)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:753)
	at org.testng.TestRunner.run(TestRunner.java:607)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:363)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)
	at org.testng.SuiteRunner.run(SuiteRunner.java:270)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
	at org.testng.TestNG.runSuites(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1096)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- org.sikuli.script.FindFailed -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- room1TestCase -->
        <test-method status="FAIL" signature="room2TestCase()[pri:3, instance:test.TestAppium@10bbd20a]" name="room2TestCase" duration-ms="379" started-at="2017-01-18T00:57:38Z" finished-at="2017-01-18T00:57:38Z">
          <exception class="org.sikuli.script.FindFailed">
            <message>
              <![CDATA[Text search currently switched off]]>
            </message>
            <full-stacktrace>
              <![CDATA[FindFailed: Text search currently switched off
  Line 1671, in file Region.java

	at org.sikuli.script.Region.wait(Region.java:1671)
	at org.sikuli.script.Region.find(Region.java:1590)
	at test.TestAppium.room2TestCase(TestAppium.java:181)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1137)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:753)
	at org.testng.TestRunner.run(TestRunner.java:607)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:363)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)
	at org.testng.SuiteRunner.run(SuiteRunner.java:270)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
	at org.testng.TestNG.runSuites(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1096)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- org.sikuli.script.FindFailed -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- room2TestCase -->
        <test-method status="PASS" signature="lobby2TestCase()[pri:4, instance:test.TestAppium@10bbd20a]" name="lobby2TestCase" duration-ms="8224" started-at="2017-01-18T00:57:38Z" finished-at="2017-01-18T00:57:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lobby2TestCase -->
        <test-method status="FAIL" signature="room3TestCase()[pri:5, instance:test.TestAppium@10bbd20a]" name="room3TestCase" duration-ms="3260" started-at="2017-01-18T00:57:47Z" finished-at="2017-01-18T00:57:50Z">
          <exception class="org.sikuli.script.FindFailed">
            <message>
              <![CDATA[can not find D:/Wanka project/New Images/lobby2Room1/Room3_region.png on the screen.]]>
            </message>
            <full-stacktrace>
              <![CDATA[FindFailed: can not find D:/Wanka project/New Images/lobby2Room1/Room3_region.png on the screen.
  Line 1574, in file Region.java

	at org.sikuli.script.Region.handleFindFailed(Region.java:1574)
	at org.sikuli.script.Region.wait(Region.java:1682)
	at org.sikuli.script.Region.find(Region.java:1590)
	at test.TestAppium.room3TestCase(TestAppium.java:271)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1137)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:753)
	at org.testng.TestRunner.run(TestRunner.java:607)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:363)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)
	at org.testng.SuiteRunner.run(SuiteRunner.java:270)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
	at org.testng.TestNG.runSuites(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1096)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- org.sikuli.script.FindFailed -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- room3TestCase -->
      </class> <!-- test.TestAppium -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
